"""
Django settings for tesis_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# tesis_backend/settings.py
import os
from pathlib import Path
import dotenv # Importar dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Cargar variables de entorno desde .env ---
dotenv_path = BASE_DIR / '.env' # Ruta al archivo .env en la raíz del proyecto Django
dotenv.load_dotenv(dotenv_path=dotenv_path)
# ----------------------------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# --- Leer SECRET_KEY desde .env ---
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-valor-default-inseguro-si-no-hay-env') # Añade un default inseguro por si acaso

# SECURITY WARNING: don't run with debug turned on in production!
# --- Leer DEBUG desde .env ---
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True' # Default es False si no está en .env

# --- Leer ALLOWED_HOSTS desde .env (opcional, pero recomendado) ---
ALLOWED_HOSTS_STRING = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1') # Default para desarrollo
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',') if host.strip()]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'optimizer.apps.OptimizerConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tesis_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tesis_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py (al final)

# Configuración CORS (Asegúrate de tenerla si llamas desde origen diferente)
CORS_ALLOWED_ORIGINS = [
    # Añade aquí los orígenes permitidos si despliegas (ej. tu app web)
    # Para desarrollo local con emuladores/dispositivos, a menudo se necesita:
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # Considera añadir los puertos de Flutter si son fijos o usar:
    # CORS_ALLOW_ALL_ORIGINS = True # ¡SOLO PARA DESARROLLO!
]
CORS_ALLOW_ALL_ORIGINS = DEBUG # Permitir todo en Debug, restringir en producción